In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("../data/previous_lecture_grades.csv")

df.head()

    Name  StudyHours  Grade
0    Dan       10.00   50.0
1  Joann       11.50   50.0
2  Pedro        9.00   47.0
3  Rosie       16.00   97.0
4  Ethan        9.25   49.0

In [3]:
df

         Name  StudyHours  Grade
0         Dan       10.00   50.0
1       Joann       11.50   50.0
2       Pedro        9.00   47.0
3       Rosie       16.00   97.0
4       Ethan        9.25   49.0
5       Vicky        1.00    3.0
6    Frederic       11.50   53.0
7      Jimmie        9.00   42.0
8      Rhonda        8.50   26.0
9    Giovanni       14.50   74.0
10  Francesca       15.50   82.0
11      Rajab       13.75   62.0
12    Naiyana        9.00   37.0
13       Kian        8.00   15.0
14      Jenny       15.50   70.0
15     Jakeem        8.00   27.0
16     Helena        9.00   36.0
17      Ismat        6.00   35.0
18      Anila       10.00   48.0
19       Skye       12.00   52.0
20     Daniel       12.50   63.0
21      Aisha       12.00   64.0
22       Bill        8.00    NaN
23        Ted         NaN    NaN

In [6]:
data = df.dropna(subset=["Grade"])

In [7]:
data

         Name  StudyHours  Grade
0         Dan       10.00   50.0
1       Joann       11.50   50.0
2       Pedro        9.00   47.0
3       Rosie       16.00   97.0
4       Ethan        9.25   49.0
5       Vicky        1.00    3.0
6    Frederic       11.50   53.0
7      Jimmie        9.00   42.0
8      Rhonda        8.50   26.0
9    Giovanni       14.50   74.0
10  Francesca       15.50   82.0
11      Rajab       13.75   62.0
12    Naiyana        9.00   37.0
13       Kian        8.00   15.0
14      Jenny       15.50   70.0
15     Jakeem        8.00   27.0
16     Helena        9.00   36.0
17      Ismat        6.00   35.0
18      Anila       10.00   48.0
19       Skye       12.00   52.0
20     Daniel       12.50   63.0
21      Aisha       12.00   64.0

In [17]:
PASS_LIMIT = 50

In [18]:
data["Passed"] = data["Grade"] >= PASS_LIMIT

/tmp/ipykernel_818436/1179549180.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Passed"] = data["Grade"] >= PASS_LIMIT

In [19]:
data

         Name  StudyHours  Grade  Passed
0         Dan       10.00   50.0    True
1       Joann       11.50   50.0    True
2       Pedro        9.00   47.0   False
3       Rosie       16.00   97.0    True
4       Ethan        9.25   49.0   False
5       Vicky        1.00    3.0   False
6    Frederic       11.50   53.0    True
7      Jimmie        9.00   42.0   False
8      Rhonda        8.50   26.0   False
9    Giovanni       14.50   74.0    True
10  Francesca       15.50   82.0    True
11      Rajab       13.75   62.0    True
12    Naiyana        9.00   37.0   False
13       Kian        8.00   15.0   False
14      Jenny       15.50   70.0    True
15     Jakeem        8.00   27.0   False
16     Helena        9.00   36.0   False
17      Ismat        6.00   35.0   False
18      Anila       10.00   48.0   False
19       Skye       12.00   52.0    True
20     Daniel       12.50   63.0    True
21      Aisha       12.00   64.0    True

In [20]:
data["Passed"].value_counts()

True     11
False    11
Name: Passed, dtype: int64

In [23]:
HOURS_LIMIT = 10
data["HighHours"] = data["StudyHours"] >= HOURS_LIMIT

/tmp/ipykernel_818436/144843216.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["HighHours"] = data["StudyHours"] >= HOURS_LIMIT

In [24]:
data["HighHours"].value_counts()

True     12
False    10
Name: HighHours, dtype: int64

In [25]:
table = pd.crosstab(data["HighHours"], data["Passed"])
table

Passed     False  True
HighHours
False         10      0
True           1     11

In [26]:
passed_high = table.loc[True, True]
failed_high = table.loc[True, False]

In [27]:
passed_high

11

In [28]:
failed_high

1

In [30]:
passed_low = table.loc[False,True]
passed_low

0

In [31]:
failed_low = table.loc[False,False]
failed_low

10

In [38]:
thresholds = [6,8,9, 10, 11.5, 12, 13, 14, 15,]
results = []


for threshold in thresholds:
    high_hours = data["StudyHours"] >= threshold
    passed = data["Passed"]
    
    passed_high = ( (high_hours == True) & (passed == True) ).sum()
    failed_high = ((high_hours == True) & (passed == False)).sum()

    passed_low = ((high_hours == False) & (passed == True)).sum()
    failed_low = ((high_hours == False) & (passed == False)).sum()
    results.append({
        "threshold": threshold,
        "passed_high": passed_high,
        "failed_high": failed_high,
        "passed_low": passed_low,
        "failed_low": failed_low,
    })
    print(passed_high)

11
11
11
11
10
8
5
4
3

In [39]:
or_table = pd.DataFrame(results)

or_table

   threshold  passed_high  failed_high  passed_low  failed_low
0        6.0           11           10           0           1
1        8.0           11            9           0           2
2        9.0           11            6           0           5
3       10.0           11            1           0          10
4       11.5           10            0           1          11
5       12.0            8            0           3          11
6       13.0            5            0           6          11
7       14.0            4            0           7          11
8       15.0            3            0           8          11

## 2. Normy

Norma mierzy „długość” wektora.

Norma **L2**, czyli euklidesowa:

$$
\|x\|_2 = \sqrt{x_1^2+x_2^2+\ldots+x_p^2}
$$

Norma **L1**, czyli Manhattan:

$$
\|x\|_1 = |x_1|+|x_2|+\ldots+|x_p|
$$

Norma maksimum:

$$
\|x\|_\infty = \max_j |x_j|
$$

## Scaling

In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler, MinMaxScaler, normalize
from sklearn.metrics.pairwise import euclidean_distances, cosine_similarity

In [44]:
people = pd.DataFrame({
    'person': ['A', 'B', 'C'],
    'age': [22, 24, 55],
    'income': [4000, 9000, 9500]    
    'occupation':['','','']
})

In [46]:
X_raw = people[['age','income']].values
D_raw = euclidean_distances(X_raw)

In [47]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_raw)
D_scaled = euclidean_distances(X_scaled, X_scaled)

In [48]:
print('Odległośi bez skalowania:')
print(pd.DataFrame(D_raw, index=people['person'], columns=people['person']))

Odległośi bez skalowania:
person            A            B            C
person
A          0.000000  5000.000400  5500.098999
B       5000.000400     0.000000   500.960078
C       5500.098999   500.960078     0.000000

In [49]:
print('\nOdległości po StandardScaler:')
print(pd.DataFrame(D_scaled, index=people['person'], columns=people['person']))

Odległości po StandardScaler:
person         A         B         C
person
A       0.000000  2.017816  3.110799
B       2.017816  0.000000  2.061880
C       3.110799  2.061880  0.000000

In [50]:
scaled_people = pd.DataFrame(X_scaled, columns=['age_scaled', 'income_scaled'])
scaled_people.insert(0, 'person', people['person'])
scaled_people

  person  age_scaled  income_scaled
0      A   -0.772268      -1.409428
1      B   -0.639879       0.604040
2      C    1.412147       0.805387

## 5. StandardScaler i MinMaxScaler

StandardScaler:

$$
z = \frac{x-\mu}{\sigma}
$$

MinMaxScaler:

$$
x' = \frac{x-x_{min}}{x_{max}-x_{min}}
$$

StandardScaler jest naturalny dla modeli liniowych, SVM, PCA i regularyzacji. MinMaxScaler bywa wygodny, gdy chcemy mieć wartości w przedziale $[0,1]$.

## 6. Cosine similarity

Cosine similarity porównuje kierunek wektorów, a nie ich długość:

$$
\cos(x,y)=\frac{x\cdot y}{\|x\|\|y\|}
$$

W tekstach i embeddingach często interesuje nas kierunek: czy dwa dokumenty mają podobny profil słów, nawet jeśli jeden jest dużo dłuższy.

1:4

## 1. Prawdopodobieństwo, odds i log-odds

Prawdopodobieństwo zdarzenia oznaczamy tutaj jako:

$$
0 \le p \le 1
$$

Dla samych wzorów na `odds` i `log-odds` zwykle zakładamy:

$$
0 < p < 1
$$

bo dla $p=0$ lub $p=1$ log-odds są wartościami granicznymi: $-\infty$ albo $+\infty$.

**Odds** to stosunek „sukcesów” do „porażek”:

$$
odds = \frac{p}{1-p}
$$

Odwrotne przejście z odds do prawdopodobieństwa:

$$
p = \frac{odds}{1+odds}
$$

**Log-odds**, czyli **logit**, to logarytm z odds:

$$
logit(p) = \log\left(\frac{p}{1-p}\right)
$$

Intuicja: prawdopodobieństwo `p` żyje w przedziale od 0 do 1, ale `logit(p)` żyje na całej osi rzeczywistej. Dzięki temu w regresji logistycznej możemy modelować log-odds liniowo:

$$
logit(p) = X\beta
$$

1/4    4/1